### ISSUE TITLE
Add support for non-pinned requirements

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/upgrade-requirements.py#6]
This will solve the `Error: Can only work with pinned requirements for now.` case.

**Comment by jamesbroadhead** [comment]
^ this code-path should probably raise rather than fall-through to the next line.

```
Reading ./scripts/env/requirements.txt...
Error: Can only work with pinned requirements for now.
Traceback (most recent call last):
  File "/Users/jbo/venv/default/bin/upgrade-requirements", line 11, in <module>
    load_entry_point('upgrade-requirements==1.7.0', 'console_scripts', 'upgrade-requirements')()
  File "/Users/jbo/venv/default/lib/python3.7/site-packages/upgrade_requirements.py", line 58, in main
    name, version = requirement.split('==')
ValueError: not enough values to unpack (expected 2, got 1)
```
